name: 'workflow'
on:
  push:
    branches:
      - master

jobs:
  test-update-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update values.yaml
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'manifest.yaml'
          propertyPath: 'spec.template.spec.containers[0].image'
          value: andersonfcz/tcc-gitops:1.1
          commitChange: true
          message: 'ci update'
          branch: 'master'
